// Safety routing (non-negotiable 4, GR-4): health, safety and emergency questions never reach the
// matcher, show the fixed guide-and-emergency card and are not stored.
//
// Conservative by design: a false positive sends a guest to the guide, which is safe. A false
// negative is the failure that matters, so this list errs towards triggering.
//
// DRAFT LEXICON: the word lists are a first draft for Bee and Preet to review. Words that are
// common in ordinary tour questions are left out on purpose and recorded in the tests:
// bare "help"/"hilfe"/"hulp"/"hjalp" (can you help me buy coffee?), "fire" (roasting), "burn"
// (burnt coffee), "faint" (a faint aroma), "bite" (a bite to eat).
//
// Entries are written in plain letters. They are normalized when this module loads, so
// diacritics may be used here, and matching is whole word or whole phrase only: `doctoral`
// does not hit `doctor`. German compounds are listed explicitly because of that rule.

import { normalize } from "../text/normalize.ts";
import type { VisitorLang } from "../types.ts";

export const SAFETY_LEXICON: Record<VisitorLang, readonly string[]> = {
  en: [
    // injury and emergency
    "emergency",
    "hurt",
    "injured",
    "injury",
    "wounded",
    "bleeding",
    "blood",
    "unconscious",
    "fainted",
    "choking",
    "breathe",
    "heart attack",
    "accident",
    // medical help
    "doctor",
    "nurse",
    "hospital",
    "clinic",
    "ambulance",
    "paramedic",
    "medicine",
    "medication",
    "pharmacy",
    // illness and conditions
    "sick",
    "ill",
    "pain",
    "fever",
    "vomit",
    "vomiting",
    "allergic",
    "allergy",
    "pregnant",
    "diabetic",
    "diabetes",
    "asthma",
    // poisoning and animals
    "poison",
    "poisoned",
    "snake",
    "snakebite",
    "bitten",
    "stung",
    // lost, danger, crime
    "lost",
    "danger",
    "dangerous",
    "police",
    "robbed",
    "stolen",
    "thief",
    "attacked",
    "hurts",
    "hurting",
    "bleed",
    "bleeds",
    "snakes",
    "poisonous",
    "doctors",
    "accidents",
    "injuries",
    "dizzy",
    "collapsed",
    "unwell",
    "sunstroke",
    "heatstroke",
    "dehydrated",
    "drowning",
    "drowned",
    "throwing up",
    "safe to drink",
    "on fire",
    "caught fire",
    "broke my",
    "broken arm",
    "broken leg",
    "broken bone",
    "broken bones",
  ],
  de: [
    "notfall",
    "notruf",
    "verletzt",
    "verletzung",
    "blutet",
    "blutung",
    "blut",
    "bewusstlos",
    "unfall",
    "arzt",
    "arztin",
    "arzte",
    "notarzt",
    "krankenhaus",
    "krankenwagen",
    "rettungswagen",
    "ambulanz",
    "apotheke",
    "medikament",
    "medikamente",
    "krank",
    "schmerzen",
    "fieber",
    "allergisch",
    "allergie",
    "schwanger",
    "diabetes",
    "asthma",
    "vergiftung",
    "vergiftet",
    "schlange",
    "gebissen",
    "gestochen",
    "verirrt",
    "verlaufen",
    "gefahr",
    "gefährlich",
    "polizei",
    "bestohlen",
    "uberfallen",
    "kopfschmerzen",
    "bauchschmerzen",
    "zahnschmerzen",
    "brandwunde",
    "schlangen",
    "giftig",
    "schwindelig",
    "kollabiert",
    "sonnenstich",
    "hitzeschlag",
    "dehydriert",
    "ertrinken",
    "ertrunken",
    "verletzte",
    "gebrochen",
    "tut weh",
  ],
  nl: [
    "noodgeval",
    "nooddienst",
    "gewond",
    "verwond",
    "bloed",
    "bloeden",
    "bewusteloos",
    "ongeluk",
    "ongeval",
    "dokter",
    "arts",
    "ziekenhuis",
    "ambulance",
    "apotheek",
    "medicijn",
    "medicijnen",
    "ziek",
    "pijn",
    "koorts",
    "allergisch",
    "allergie",
    "zwanger",
    "suikerziekte",
    "astma",
    "vergif",
    "vergiftigd",
    "slang",
    "gebeten",
    "gestoken",
    "verdwaald",
    "de weg kwijt",
    "gevaar",
    "gevaarlijk",
    "politie",
    "bestolen",
    "overvallen",
    "hoofdpijn",
    "buikpijn",
    "tandpijn",
    "brandwond",
    "slangen",
    "giftig",
    "duizelig",
    "ingestort",
    "zonnesteek",
    "uitgedroogd",
    "verdrinken",
    "verdronken",
    "gebroken",
    "doet pijn",
  ],
  sv: [
    "nödsituation",
    "nödläge",
    "skadad",
    "skadade",
    "skadat",
    "blod",
    "blöder",
    "medvetslös",
    "olycka",
    "läkare",
    "doktor",
    "sjukhus",
    "ambulans",
    "apotek",
    "medicin",
    "sjuk",
    "ont",
    "feber",
    "allergisk",
    "allergi",
    "gravid",
    "diabetes",
    "astma",
    "förgiftning",
    "förgiftad",
    "orm",
    "biten",
    "stucken",
    "vilse",
    "fara",
    "farlig",
    "polis",
    "bestulen",
    "överfallen",
    "huvudvärk",
    "magont",
    "tandvärk",
    "brännskada",
    "ormar",
    "giftig",
    "yr",
    "kollapsade",
    "solsting",
    "uttorkad",
    "drunknar",
    "drunknade",
    "bruten",
    "gjort illa",
  ],
};

// Normalized once. Phrases are padded the same way as the text, so " heart attack " matches whole
// words only.
const PATTERNS: readonly string[] = Object.values(SAFETY_LEXICON)
  .flat()
  .map((phrase) => normalize(phrase));

/** True when the text mentions anything in the multilingual lexicon. Pure; stores nothing. */
export function decideSafety(text: string): boolean {
  const padded = normalize(text);
  return PATTERNS.some((pattern) => padded.includes(pattern));
}
