"""English transcripts with word timestamps (ElevenLabs speech-to-text), and the comparison with
Noor's script. Build time only: this never runs at guest runtime.

The subtitle is what Preet actually said, so every difference from the script is listed for her
to confirm. Her confirmation is an entry in content/<farm>/checks.json that carries the SHA-256
of the transcript she approved; re-transcribing changes the hash and so withdraws the check.
"""

from __future__ import annotations

import difflib
import hashlib
import json
import os
import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path

STT_URL = "https://api.elevenlabs.io/v1/speech-to-text"
STT_MODEL = "scribe_v2"  # batch model per the ElevenLabs docs; confirmed by the first live run


class TranscribeError(Exception):
    pass


# ---- calling the API -------------------------------------------------------------------------


def api_key(env_file: Path | None = None) -> str:
    """ELEVENLABS_API_KEY from the environment or pipeline/.env (gitignored). Build time only."""
    key = os.environ.get("ELEVENLABS_API_KEY", "").strip()
    if not key and env_file and env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            name, _, value = line.partition("=")
            if name.strip() == "ELEVENLABS_API_KEY":
                key = value.strip().strip("\"'")
    if not key:
        raise TranscribeError(
            "ELEVENLABS_API_KEY is not set. Put it in pipeline/.env (gitignored) to run the "
            "transcript step; it is never used at guest runtime."
        )
    return key


def request_transcript(audio_path: Path, key: str, language_code: str = "eng") -> dict:
    import httpx

    with audio_path.open("rb") as fh:
        response = httpx.post(
            STT_URL,
            headers={"xi-api-key": key},
            data={"model_id": STT_MODEL, "language_code": language_code, "timestamps_granularity": "word"},
            files={"file": (audio_path.name, fh, "audio/mp4")},
            timeout=120,
        )
    if response.status_code != 200:
        raise TranscribeError(f"speech-to-text failed ({response.status_code}): {response.text[:300]}")
    return response.json()


def parse_response(payload: dict) -> list[dict]:
    """Words (not spacing or audio events) with start and end seconds."""
    words = [
        {"text": w["text"], "start": round(float(w["start"]), 3), "end": round(float(w["end"]), 3)}
        for w in payload.get("words", [])
        if w.get("type", "word") == "word"
    ]
    if not words:
        raise TranscribeError("the response has no words")
    return words


# ---- comparing with the script ---------------------------------------------------------------

_NUMBERS = {
    "zero": "0", "one": "1", "two": "2", "three": "3", "four": "4", "five": "5", "six": "6",
    "seven": "7", "eight": "8", "nine": "9", "ten": "10", "eleven": "11", "twelve": "12",
    "thirteen": "13", "fourteen": "14", "fifteen": "15", "sixteen": "16", "seventeen": "17",
    "eighteen": "18", "nineteen": "19", "twenty": "20",
}  # fmt: skip


def normalize_words(text: str) -> list[str]:
    """Lowercase, drop punctuation (keeping apostrophes inside words), spelled-out numbers to digits."""
    text = text.lower().replace("’", "'")
    words = re.findall(r"[a-z0-9]+(?:'[a-z]+)?", text)
    return [_NUMBERS.get(w, w) for w in words]


@dataclass(frozen=True)
class Difference:
    kind: str  # "replaced", "missing" (in the recording) or "extra" (in the recording)
    script: str
    heard: str
    position: int  # word index in the script


def compare(script: str, heard: str) -> list[Difference]:
    a, b = normalize_words(script), normalize_words(heard)
    diffs: list[Difference] = []
    for tag, i1, i2, j1, j2 in difflib.SequenceMatcher(a=a, b=b, autojunk=False).get_opcodes():
        if tag == "equal":
            continue
        kind = {"replace": "replaced", "delete": "missing", "insert": "extra"}[tag]
        diffs.append(Difference(kind, " ".join(a[i1:i2]), " ".join(b[j1:j2]), i1))
    return diffs


def transcript_sha256(text: str) -> str:
    return hashlib.sha256(" ".join(normalize_words(text)).encode()).hexdigest()


def comparison_markdown(rows: list[tuple[int, str, str, list[Difference]]]) -> str:
    """The report Preet reads: one section per clip, every difference listed."""
    lines = [
        "# English transcripts compared with Noor's script",
        "",
        "Generated by `asknoor.build --steps transcribe`. Subtitles use what was actually said. "
        "Preet confirms each clip by signing its entry in `checks.json`.",
        "",
    ]
    for clip, script, heard, diffs in rows:
        lines += [f"## Clip {clip}: {'match' if not diffs else 'differs'}", "", f"- Script: {script}", f"- Heard: {heard}"]
        for d in diffs:
            lines.append(f"- {d.kind} at script word {d.position}: script `{d.script or '-'}`, heard `{d.heard or '-'}`")
        lines.append("")
    return "\n".join(lines)


# ---- the build step --------------------------------------------------------------------------


def step_transcribe(farm: str) -> dict[int, str]:
    from .build import CONSENT_MD, REPO, BuildError, build_dir, content_dir, load_registry
    from .consent import ConsentError, require_confirmed

    # Sending a person's voice to a third-party service needs its own consent, separate from
    # dubbing. Checked before the key is even read.
    for person in sorted({r["person"] for r in load_registry(farm) if r["lang"] == "en"}):
        try:
            require_confirmed(CONSENT_MD, person, scope="transcription")
        except ConsentError as error:
            raise BuildError(str(error)) from error

    key = api_key(REPO / "pipeline" / ".env")
    clips = json.loads((content_dir(farm) / "clips.json").read_text(encoding="utf-8"))["clips"]
    out_dir = content_dir(farm) / "transcripts" / "en"
    out_dir.mkdir(parents=True, exist_ok=True)
    rows, status = [], {}
    for clip in clips:
        n = clip["id"]
        audio_path = build_dir(farm) / "audio" / "en" / f"clip{n:02d}.m4a"
        if not audio_path.exists():
            raise BuildError(f"{audio_path} is missing: run the audio step first")
        words = parse_response(request_transcript(audio_path, key))
        heard = " ".join(w["text"] for w in words)
        diffs = compare(clip["script"]["en"], heard)
        doc = {
            "clip": n,
            "model": STT_MODEL,
            "date": date.today().isoformat(),
            "text": heard,
            "sha256": transcript_sha256(heard),
            "words": words,
        }
        (out_dir / f"clip{n:02d}.json").write_text(json.dumps(doc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        rows.append((n, clip["script"]["en"], heard, diffs))
        status[n] = "match" if not diffs else "differs"
    (out_dir / "comparison.md").write_text(comparison_markdown(rows), encoding="utf-8")
    print("transcribe: " + ", ".join(f"clip {n} {s}" for n, s in status.items()))
    return status
